name: on-pull-request

on:
  push:
    branches: ["main"]
  pull_request_target:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test pipeline foo"
    - run: echo "${{ secrets.FOO }}"
    - run: echo "and in a second commit, that does NOT change the trigger event?"
